# Generated by Django 4.1 on 2022-08-19 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_artist_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_album', to='core.album'),
        ),
    ]
